version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cookbooks
hooks:
  BeforeInstall:
    - location: codedeploy/preInstall.sh
      timeout: 30
      runas: ec2-user
  AfterInstall:
    - location: codedeploy/runChef.sh
      timeout: 300
      runas: root
